### ISSUE TITLE
found no layout file

### ISSUE THREAD

**Issue by alessandrofesti** [victoriadrake/quint-demo#1]
whe i run hugo server --config hugo.toml i get the following warning and the website does not display. Thanks

Building sites … WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/10 17:29:06 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  4  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  6  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 24 ms
Watching for changes in /home/alessandro/Scrivania/work/personal/quint-demo/{archetypes,content,static}
Watching for config changes in /home/alessandro/Scrivania/work/personal/quint-demo/hugo.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to sto

**Comment by victoriadrake** [comment]
Hello,

This is happening because `git clone` doesn't fill the theme submodule by default. Instead, use:

```bash
git clone --recurse-submodules -j8 https://github.com/victoriadrake/quint-demo.git
```

I've updated the README to reflect this. Thank you for letting me know!
