### ISSUE TITLE
Issue running demo on Windows/Git Bash

### ISSUE THREAD

**Issue by csommers79** [victoriadrake/quint-demo#2]
Getting this error after cloning the repo with submodules and then running "hugo server" on PowerShell and Git Bash

![image](https://github.com/user-attachments/assets/e6a890f9-2568-4629-ac3b-acfb995e1d76)

**Comment by victoriadrake** [comment]
Hello Chris,

I can't seem to replicate this error myself but I've pushed an update to the theme that may resolve it. Thanks for bringing this to my attention!

You can update your theme by pulling new changes from the submodule.

```sh
git submodule update --remote
```

**Comment by csommers79** [comment]
Thank you, I figured it out. On windows I had to add \r before the \n for newline character. On Sep 12, 2024, at 2:25 PM, Victoria Drake ***@***.***> wrote:﻿
Hello Chris,
I can't seem to replicate this error myself but I've pushed an update to the theme that may resolve it. Thanks for bringing this to my attention!
You can update your theme by pulling new changes from the submodule.
git submodule update --remote
